/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mycompany.habitos_saludables.vista;

import com.mycompany.habitos_saludables.usuario.Usuario;
import java.util.List;

/**
 *
 * @author Calavera
 */
public class EstadisticasVista extends javax.swing.JFrame {

    private Usuario usuarioActivo;
    private List<Usuario> usuarios;

    /** Creates new form EstadisticasPanel */
    public EstadisticasVista(Usuario usuarioActivo, List<Usuario> usuarios) {
        this.usuarioActivo = usuarioActivo;
        this.usuarios = usuarios;
        initComponents();
        setLocationRelativeTo(null);
        mostrarEstadisticas();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Estadísticas Semanales");
        jLabel4.setText("Aquí se muestran tus registros semanales. ¡Sigue así y construye una rutina cada vez más saludable!");

        btnVolver.setText("Volver al menú");
        btnVolver.addActionListener(evt -> {
            new HomeVista(usuarioActivo, usuarios).setVisible(true);
            this.dispose();
        });

        jTextArea1.setColumns(30);
        jTextArea1.setRows(12);
        jTextArea1.setEditable(false);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(btnVolver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVolver)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mostrarEstadisticas() {
        StringBuilder sb = new StringBuilder();
        java.util.List<com.mycompany.habitos_saludables.registro.RegistroDiario> registros = usuarioActivo.getRegistros();
        if (registros.isEmpty()) {
            sb.append("No hay registros para mostrar.\n");
        } else {
            for (com.mycompany.habitos_saludables.registro.RegistroDiario reg : registros) {
                sb.append("Día: ").append(reg.getDia()).append("\n");
                for (var entry : reg.getHabitosCompletados().entrySet()) {
                    sb.append("  - ").append(entry.getKey())
                      .append(": ").append(entry.getValue() ? "Completado" : "No completado").append("\n");
                }
                sb.append("\n");
            }
        }
        jTextArea1.setText(sb.toString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
